/*
================================================================================
    main.c - RayClay `opsdash`: the demo runner (showcase mode)
================================================================================

    The thin desktop/web entry point for the ops-dashboard benchmark/showcase app.
    It is the ONLY translation unit that touches the RC_ runner (RC_App*): it opens a
    real window with real clock + input, seeds the app once, and drives the SAME pure
    core (opsdash_update / opsdash_layout) the benchmark harness drives - only the
    clock/seed/input source differs (see opsdash_app.h). The demo adds a floating perf
    HUD via opsdash_demo_chrome; the bench never runs it.

    Same source -> native desktop window AND web (cmake --preset web). Zero-asset: the
    whole fleet is generated by the backend, so there is nothing to ship alongside it.
    Headless smoke: RAYCLAY_MAX_FRAMES=N -> opens, draws N frames, exits 0.

    App #6 of the standardised production benchmark/showcase apps, and the one the
    render-only static-island experiment (L1) needs: a large unchanged subtree beside
    a small changing one. See opsdash_app.h for why that shape is the whole point.

    Build target: rayclay_bench_opsdash
================================================================================
*/
#include "opsdash_app.h"

static void demo_update(RC_App *app, void *userData) {
    AppState *st = (AppState *)userData;
    if (!st->seeded)
        opsdash_seed(st, 0x0D5DA5EEu);   /* a fixed demo seed */
    AppCtx ctx = app_demo_ctx(app);
    opsdash_update(st, &ctx);
}

static void demo_layout(RC_App *app, void *userData) {
    AppState *st = (AppState *)userData;
    AppCtx ctx = app_demo_ctx(app);
    opsdash_layout(st, &ctx);
    opsdash_demo_chrome(st, &ctx);
}

int main(void) {
    static AppState state;   /* zero-init; opsdash_seed fills it on frame 1 */

    static const float font_sizes[F_COUNT] = {
        [F_SMALL] = 12.0f,
        [F_BODY]  = 14.0f,
        [F_MONO]  = 14.0f,
        [F_MD]    = 20.0f,
        [F_TITLE] = 26.0f,
    };

    rcSetStyle(rcStyleDark());

    RC_AppOptions opts = {
        .width               = 1280,
        .height              = 720,
        .title               = "RayClay Fleet Operations",
        .clearColor          = rcGetStyle().background,
        .fontSizes           = font_sizes,
        .fontCount           = F_COUNT,
        .scratchArenaBytes   = 4096,      /* backs rcFormat in the demo HUD only */
        .startLayoutElements = 4096,      /* 48 cards x ~10 elements + nav + rail */
        .nativeFrame         = true,
        .titlebarHeight      = 52,
        .titlebar            = { .custom = true },   /* the topbar IS the titlebar */
        .updateCallback            = demo_update,
        .layoutCallback            = demo_layout,
        .userData            = &state,
        /* Unlike the other bench apps, this one's content genuinely animates: the
           telemetry rail advances a pulse and rolls a counter every frame, so the
           picture never settles and there is nothing for the on-demand runner to park
           on. Continuous is the honest mode here rather than a concession to the HUD.
           Note: the lesson for a real app is still the one ex04 teaches. A live
           readout is an animation and you pay for it, so put one on screen only when
           you mean to. An ops dashboard means to. Only the demo runner is affected;
           the headless bench harness injects a fixed dt and never calls rcRunApp. */
        .renderMode          = RC_RENDER_CONTINUOUS,
    };

    return rcRunApp(&opts);
}
